project 'PolyvVodSDKDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PolyvVodSDKDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PolyvVodSDKDemo
  pod 'XRCarouselView'
  pod 'JMRoundedCorner'
  pod 'YYWebImage'
  pod 'NinaPagerView', '~> 1.6.2'

  target 'PolyvVodSDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PolyvVodSDKDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
