project 'PolyvVodSDKDemo.xcodeproj'

platform :ios, '8.0'
inhibit_all_warnings!

target 'PolyvVodSDKDemo' do
	# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
	# use_frameworks!

	# Pods for PolyvVodSDKDemo
	pod 'XRCarouselView'
	pod 'YYWebImage'
	pod 'FDStackView'

	# PLVVodSDK
	# pod 'PolyvVodSDK', :path => "../../PolyvVodSDK"
	# ⤵ development "CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES" => "YES"
	pod 'PolyvIJKPlayer'
	pod 'PolyvAliHttpDNS'
	pod 'PLVMarquee'
	pod 'PLVTimer'
	pod 'PLVNetworkDiagnosisTool'
	pod 'SSZipArchive'

	# POLYV Open Source
	pod 'PLVVodDanmu'
	pod 'PLVSubtitle'

	target 'PolyvVodSDKDemoTests' do
		inherit! :search_paths
		# Pods for testing
	end

	target 'PolyvVodSDKDemoUITests' do
		inherit! :search_paths
		# Pods for testing
	end

end
